'use client'

import React from 'react'
import { Info, BookOpen, Tent, Trophy } from 'lucide-react'

export type FaqTabKey = 'general' | 'courses' | 'camps' | 'competition'

export const faqData: Record<FaqTabKey, { label: string; icon: React.ReactNode; items: Array<{ question: string; answer: string | React.ReactNode }> }> = {
  general: {
    label: 'General',
    icon: <Info className="w-4 h-4" />,
    items: [
      { question: "What is the student-to-teacher ratio?", answer: "We maintain a low ratio of 6:1 to ensure every student gets personal attention and hands-on guidance during building and coding phases." },
      { question: "Can my child join if they have no experience?", answer: "Absolutely! Our 'RoboQuests' and 'LaunchPad' programs are designed specifically for beginners. We also offer a free 1-hour trial class to assess their level and interest." },
      { question: "Where are your campuses located?", answer: "We have campuses in Bellevue (Main and Bel-Red) and Issaquah, as well as programs at partner schools like St. Louise." }
    ]
  },
  courses: {
    label: 'Courses',
    icon: <BookOpen className="w-4 h-4" />,
    items: [
      { question: "What types of courses does Blaze Robotics Academy offer?", answer: "We offer a range of courses designed to enhance skills in robotics and STEM, including introductory sessions for beginners, advanced programming, robotics engineering, and competition preparation courses." },
      { question: "Are there prerequisites for any of the courses?", answer: "Some advanced courses may have prerequisites, such as basic knowledge of programming or prior completion of specific introductory courses. Check the course description for details." },
      { question: "How long do courses typically last?", answer: "Our standard courses run in a 10-week format, focusing on a broad range of robotics and STEM topics. For those interested in competition-specific training, we offer both a 10-week format during the school year and a 2-week intensive format in the summer, detailed in a separate FAQ." },
      { question: "How are your competition courses structured throughout the year?", answer: "During the school year, our competition courses are offered in a 10-week format, with sessions lasting 3 hours per week, totaling 30 hours. This format is designed to integrate seamlessly with students' regular schedules, providing ongoing, in-depth preparation for competitions. In the summer, we condense the same comprehensive 30-hour curriculum into a 2-week intensive course, running full days from 9 AM to 3 PM. Despite the difference in delivery time frames, both courses cover identical content, ensuring all students receive the same level of preparation for joining the competition team." },
      { question: "What is the class size for each course?", answer: "We maintain small class sizes to ensure personalized attention and an optimal learning environment, typically capping classes at 10-15 students." },
      { question: "Can I enroll in multiple courses at once?", answer: "Yes, students are welcome to enroll in multiple courses as long as the schedule permits. We recommend considering workload and course intensity when planning." },
      { question: "What materials will I need for the courses?", answer: "Most materials and equipment are provided. However, for certain courses, students may be advised to bring their laptop or subscribe to specific software. Check the course requirements for details." },
      { question: "Who teaches the courses?", answer: "Our courses are taught by experienced instructors and competition team coaches with extensive backgrounds in robotics, engineering, and STEM education." },
      { question: "What happens if I miss a class?", answer: "We understand that conflicts can arise. While we encourage full attendance to get the most out of each course, missed classes can often be made up through session recordings or additional materials, depending on the instructor's policy." },
      { question: "Do students need to bring their own laptop?", answer: "For our introductory courses and camps, we provide all necessary equipment including laptops and iPads. For competitive teams, having a personal laptop is recommended for working on code at home, but not required in class." },
      { question: "Are the robot kits shared?", answer: "No. We provide a 1:1 hardware ratio. Every student works with their own dedicated robot kit during the duration of the class to ensure maximum hands-on time." },
      { question: "What is the refund policy for courses?", answer: (<div className="space-y-2"><p>At Blaze Robotics Academy, we understand that plans can change. Here&apos;s our refund policy for courses:</p><ul className="list-disc list-inside space-y-1 ml-4"><li><strong>100% of refund</strong> minus a 3% fee (+ any applicable taxes) until 15 day(s) before the beginning of the activity</li><li><strong>Prorated credit</strong> after the start of the activity, based on the number of classes remaining at the time of cancellation</li></ul><p>To request a refund, please contact our administration team with your registration details and the reason for cancellation. We aim to process all refunds within 14 business days.</p></div>) }
    ]
  },
  camps: {
    label: 'Camps',
    icon: <Tent className="w-4 h-4" />,
    items: [
      { question: "What age groups do you cater to?", answer: "Our camps are designed for students in elementary, middle, and high school, with age-appropriate activities for each group." },
      { question: "Do I need any prior experience in robotics to join a camp?", answer: "No prior experience is necessary! Our camps are structured to welcome beginners and challenge those with previous experience." },
      { question: "How are campers grouped in each camp?", answer: "Campers are grouped by age and skill level to ensure everyone is learning and engaging at a pace that suits them best." },
      { question: "What is the daily schedule for the camps?", answer: (<div className="space-y-2"><p>Our camps run from 9:00 AM to 3:00 PM, Monday through Friday. Here&apos;s what a typical day looks like:</p><ul className="list-disc list-inside space-y-1 ml-4"><li><strong>9:00 AM - 10:30 AM:</strong> Morning session focused on interactive instruction and hands-on activities.</li><li><strong>10:30 AM - 10:45 AM:</strong> Short break.</li><li><strong>10:45 AM - 12:00 PM:</strong> Continuation of robotics projects and engaging learning activities.</li><li><strong>12:00 PM - 12:30 PM:</strong> Lunch break. Campers can enjoy their packed lunches or opt for our provided lunch selections.</li><li><strong>12:30 PM - 1:00 PM:</strong> Team-building activities designed to foster collaboration and strengthen teamwork among campers.</li><li><strong>1:00 PM - 2:40 PM:</strong> Afternoon session emphasizing project development and teamwork.</li><li><strong>2:40 PM - 3:00 PM:</strong> End-of-day wrap-up, including project reviews and setting goals for the next day.</li></ul><p>This structured yet flexible schedule ensures each camper gets the most out of their day, blending learning, fun, and essential social skills development.</p></div>) },
      { question: "Who teaches the camps?", answer: "Our camps are taught by experienced instructors and competition team coaches who are passionate about STEM education and robotics." },
      { question: "What is the camper to instructor ratio?", answer: "We maintain a low camper to instructor ratio to ensure personalized attention and a supportive learning environment." },
      { question: "Can I sign up for more than one camp?", answer: "Absolutely! We encourage campers to explore different areas of interest by signing up for multiple camps throughout the summer." },
      { question: "How can I progress after attending a camp?", answer: "Campers interested in furthering their robotics journey can enroll in our courses and even join our competitive teams to apply their skills in real-world scenarios." },
      { question: "What should I bring to camp?", answer: "Campers should bring their lunch (unless opting for our provided options), a water bottle, and any snacks they might want throughout the day. All robotics equipment will be provided." },
      { question: "Are there any lunch options available at camp?", answer: "Yes, we offer a variety of lunch options from popular local vendors, including pizza, sandwiches, and more. We also provide facilities for those who prefer to bring their own lunch." },
      { question: "Is there a lot of screen time involved?", answer: "While our camp does involve some screen time for programming and design activities, we are mindful of balancing digital engagement with plenty of hands-on learning and physical team-building activities. Screen time is structured and purposeful, aimed at enhancing learning while ensuring that campers also enjoy ample time away from screens. Our daily schedule incorporates a variety of activities that encourage movement, collaboration, and creativity, minimizing the potential for screen fatigue." },
      { question: "What is the daily schedule for full-day camps?", answer: "Camps typically run from 9:00 AM to 4:00 PM. The morning focuses on hardware engineering, while the afternoon is dedicated to programming, 3D design, and team challenges." },
      { question: "Is lunch provided during camp?", answer: "We offer an optional Pizza & Drink package for $12/day. Otherwise, parents are asked to pack a nut-free lunch and two snacks for their campers." },
      { question: "Do you offer extended care?", answer: "Yes, we offer early drop-off (8:30 AM) and late pick-up (until 5:00 PM) for an additional fee of $15/day." },
      { question: "What is the refund policy?", answer: (<div className="space-y-2"><p>At Blaze Robotics Academy, we understand that plans can change. Here&apos;s our refund policy for camps:</p><ul className="list-disc list-inside space-y-1 ml-4"><li><strong>100% of refund</strong> minus a 3% processing fee (+ any applicable taxes) until 30 day(s) before the beginning of the activity</li><li><strong>100% of credit</strong> until it starts</li></ul><p>To request a refund, please contact our administration team with your registration details and the reason for cancellation. We aim to process all refunds within 14 business days.</p></div>) }
    ]
  },
  competition: {
    label: 'Competition',
    icon: <Trophy className="w-4 h-4" />,
    items: [
      { question: "How do I join the Blaze Robotics competition team?", answer: "Joining our team starts with participating in our courses or camps to build foundational skills. We also recommend attending an informational session or reaching out directly to our team coordinator for specific joining criteria and the application process." },
      { question: "Are there prerequisites for joining the team?", answer: "Yes, we typically look for students who have completed certain courses or camps that provide the necessary robotics and teamwork skills. A passion for robotics and a commitment to the team's schedule and goals are also important." },
      { question: "What age groups can join the Blaze Robotics competition teams?", answer: "Blaze Robotics Academy welcomes students from 3rd grade through high school to join our competition teams. Our program is designed to cater to various age groups, ensuring a productive and enriching experience for all members, from elementary students to high schoolers." },
      { question: "How often do teams meet and practice?", answer: "Our VEX IQ teams typically meet once a week, focusing on a consistent and intensive learning experience. As the competition season progresses, we may offer additional practice sessions to further refine our robots and strategies. Please refer to each team level's description on our website for the most accurate schedule. Regardless of the season, our workshop provides extended access for those team members keen on extra practice time, supporting their dedication and drive to excel." },
      { question: "What competitions do Blaze teams participate in?", answer: "Blaze Robotics teams actively compete in local, out-of-state, and world VEX Robotics Competition (VRC) and VEX IQ Robotics Competition (VIQRC) events. Our commitment to challenging our teams and showcasing their talents takes us beyond local competitions; some of our teams travel out-of-state to participate in prestigious Signature Events. These varied competitive experiences, recognized by major robotics and STEM organizations, provide our students with a comprehensive platform to test their skills, innovate, and excel on a global stage." },
      { question: "Is there a fee to join the competition team?", answer: "Yes, we charge an all-inclusive team membership fee that simplifies participation costs. This single fee covers everything the team needs for the season, including team registration, tournament fees, parts, tools, field access, and facility use. Our goal is to make participation as straightforward and accessible as possible, keeping costs manageable while providing everything needed for a successful competition season." },
      { question: "What makes Blaze Robotics teams unique?", answer: "With over 20 years of combined experience, access to a dynamic workshop, and mentorship by world-winning coaches, our teams are well-equipped for success. Our students not only excel in competitions but also represent Blaze Robotics Academy's values of innovation and excellence in their academic and personal achievements." },
      { question: "When does the competition season start and end?", answer: (<div className="space-y-2"><p>Our competition season is segmented into three phases to maximize learning and competition opportunities:</p><ul className="list-disc list-inside space-y-1 ml-4"><li><strong>Early Season (June to August):</strong> This period is ideal for passionate returning students who wish to get a head start on the next season&apos;s game, which is released every May after the World Championship.</li><li><strong>Regular Season (September to February):</strong> The majority of our students enroll during the summer, with teams officially forming before the school year starts. The regular season is focused on preparing for and participating in local and out-of-state competitions.</li><li><strong>Post Season (March to May):</strong> Teams that advance to state or world championships extend their season into the post period, culminating their year either in March or at the World Championship in May.</li></ul><p>This structured approach ensures that all students, whether new or returning, have a clear pathway from preparation to competition, with opportunities to extend their involvement based on performance and commitment.</p></div>) },
      { question: "What is the refund policy for team fee?", answer: (<div className="space-y-2"><p>We understand that plans can change, and we&apos;ve structured our refund policy for teams to be as fair as possible:</p><ul className="list-disc list-inside space-y-1 ml-4"><li><strong>Full Refund:</strong> Requests made within two weeks of joining the team are eligible for a full refund, provided the regular season has not yet started.</li><li><strong>Partial Refund:</strong> Cancellations made after the initial two-week period but before the start of the regular season may qualify for a 50% refund, considering early administrative and preparatory expenses.</li><li><strong>No Refund:</strong> Once the regular season begins, refunds are not available as the team fee will have been allocated towards registration for competitions, travel, parts, tools, and other essential team-related expenses.</li></ul><p>Our policy aims to balance the academy&apos;s commitment to providing high-quality competitive experiences with the financial realities of organizing and equipping successful teams. For any refund requests or questions, please contact our administration team directly.</p></div>) },
      { question: "How do teams get formed?", answer: "Teams are formed based on age, experience level, and friend requests. We typically have 3-4 students per VEX IQ team and 4-6 students per V5 team." },
      { question: "What is the time commitment for competitive teams?", answer: "Teams meet once a week for 2 hours during the regular season, plus approximately 4-6 tournament Saturdays between November and February." },
      { question: "What is the difference between Baker and Rainier leagues?", answer: "The Rainier League is our developmental division for newer teams, while the Baker League is our premier division for advanced students seeking state and world qualifications." }
    ]
  }
}
